FROM python:3.9-slim

RUN pip install \
    dagster==0.14.15 \
    dagster-graphql==0.14.15 \
    dagit==0.14.15 \
    dagster-postgres==0.14.15 \
    dagster-docker==0.14.15 \
    protobuf==3.20.1

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml $DAGSTER_HOME
COPY workspace.grpc.yaml $DAGSTER_HOME/workspace.yaml

WORKDIR $DAGSTER_HOME